"""
Django settings for django_todolist_project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv, find_dotenv
import os
import pprint
from pymongo import MongoClient
import mongoengine
from mongoengine import connect



load_dotenv(find_dotenv())

password = os.environ.get('MONGODB_PWD')
username = os.environ.get('MONGODB_USERNAME')
dbname = os.environ.get('MONGODB_DBNAME')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q3!(ryh$8(bx@!m36^)8bg=-%uy0#&$gp5$90833g&a6^x^mg#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', 
    'django_todolist_app',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_todolist_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_todolist_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'django-todolist',  # Your MongoDB database name
#         'CLIENT': {
#             'host': 'mongodb+srv://lgwamhmmams:KiU1p2UPX9Vnz1LZ@cluster0.zdsmh.mongodb.net/django-todolist?retryWrites=true&w=majority&tlsCAFile=/etc/ssl/cert.pem',  # Replace with your MongoDB Atlas URI
#             'username': "lgwamhmmams",
#             'password': "KiU1p2UPX9Vnz1LZ",
#         }
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': '',
    }
}

connect(
    db='django-todolist',
    host='mongodb+srv://lgwamhmmams:KiU1p2UPX9Vnz1LZ@cluster0.zdsmh.mongodb.net/django-todolist?retryWrites=true&w=majority&tlsCAFile=/etc/ssl/cert.pem',
    username='lgwamhmmams',
    password='KiU1p2UPX9Vnz1LZ'
)

mongoengine.connect(host='mongodb+srv://lgwamhmmams:KiU1p2UPX9Vnz1LZ@cluster0.zdsmh.mongodb.net/django-todolist?retryWrites=true&w=majority&tlsCAFile=/etc/ssl/cert.pem')

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000", 
# ]

CORS_ALLOW_ALL_ORIGINS = True


