# Generated by Django 5.1.5 on 2025-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_todolist_app', '0001_initial'),
    ]

    
